### ISSUE TITLE
fix unstable tests

### ISSUE THREAD

**Issue by nvollmar** [apache/incubator-pekko-persistence-cassandra#33]

**Comment by nvollmar** [comment]
fixed org.apache.pekko.persistence.cassandra.query.EventsByTagSpecBackTracking

**Comment by nvollmar** [comment]
org.apache.pekko.persistence.cassandra.query.EventsByTagPersistenceIdCleanupSpec is still a bit tricky, I think it comes down to timing uncertainty. Reducing the wait time would render the test pointless.

**Comment by nvollmar** [comment]
new test popped up:
`org.apache.pekko.persistence.cassandra.EventsByTagRecoverySpec`
```must recover if snapshot is for the latest sequence nr *** FAILED *** (20 seconds, 663 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (20 seconds) during expectMsg: message matching partial function
[info]   at scala.Predef$.assert(Predef.scala:279)
[info]   at org.apache.pekko.testkit.TestKitBase.expectMsgPF(TestKit.scala:490)
[info]   at org.apache.pekko.testkit.TestKitBase.expectMsgPF$(TestKit.scala:487)
[info]   at org.apache.pekko.testkit.TestKit.expectMsgPF(TestKit.scala:984)
[info]   at org.apache.pekko.stream.testkit.TestSubscriber$ManualProbe.expectEventWithTimeoutPF(StreamTestKit.scala:737)
[info]   at org.apache.pekko.stream.testkit.TestSubscriber$ManualProbe.expectNextWithTimeoutPF(StreamTestKit.scala:714)
[info]   at org.apache.pekko.stream.testkit.TestSubscriber$ManualProbe.expectNextPF(StreamTestKit.scala:705)
[info]   at org.apache.pekko.persistence.cassandra.EventsByTagRecoverySpec.$anonfun$new$19(EventsByTagRecoverySpec.scala:217)```

**Comment by Roiocam** [comment]
`EventsByTagPersistenceIdCleanupSpec` flaky appears frequently:
- https://github.com/apache/pekko-persistence-cassandra/actions/runs/8593566355/job/23545247899
- https://github.com/apache/pekko-persistence-cassandra/actions/runs/8624962369/job/23640784807
- https://github.com/apache/pekko-persistence-cassandra/actions/runs/8657751289/attempts/1?pr=187
